#pragma once

// From glfw3.h
#define PRALINE_MOUSE_BUTTON_1         0
#define PRALINE_MOUSE_BUTTON_2         1
#define PRALINE_MOUSE_BUTTON_3         2
#define PRALINE_MOUSE_BUTTON_4         3
#define PRALINE_MOUSE_BUTTON_5         4
#define PRALINE_MOUSE_BUTTON_6         5
#define PRALINE_MOUSE_BUTTON_7         6
#define PRALINE_MOUSE_BUTTON_8         7
#define PRALINE_MOUSE_BUTTON_LAST      PRALINE_MOUSE_BUTTON_8
#define PRALINE_MOUSE_BUTTON_LEFT      PRALINE_MOUSE_BUTTON_1
#define PRALINE_MOUSE_BUTTON_RIGHT     PRALINE_MOUSE_BUTTON_2
#define PRALINE_MOUSE_BUTTON_MIDDLE    PRALINE_MOUSE_BUTTON_3

